# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N20-ysz_aS5nAAw-dvcaHlLdI3veG3Zi
"""

import numpy as np

message = np.array([1, 1, 1, 1, 1], dtype= bool)

print('Введите сообщение из 5 знаков')
messagestr = input()
for i in range(len(messagestr)) :
  if (messagestr[i] == '0') : 
    message[i] = 0
  else :
     message[i] = 1
print(message)

G = np.matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], 
              [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], 
              [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], 
              [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype = bool)

coded_message = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype = bool)


for i in range(16) :
  
  x = np.logical_xor(np.logical_and(message[0], G[0, i]), np.logical_and(message[1], G[1, i]))

  for j in range(2, 5) :
    x = np.logical_xor(x, np.logical_and(message[j], G[j, i]))
    coded_message[i] = x
coded_message

z = np.random.randint(0, 15)
print(z)
coded_message[z] = np.logical_not(coded_message[z]);
coded_message